/**
 * Seed Script — Populate subscription_plans with default plan data.
 * 
 * Usage:
 *   npx ts-node prisma/seed-plans.ts
 *
 * This script is idempotent: it uses upsert so running it multiple
 * times will update existing rows instead of duplicating them.
 */

import { prisma } from '../src/config/database';

const plans = [
  {
    plan_code: 'FREE' as const,
    name: 'Free',
    description: 'Paket gratis untuk mencoba fitur dasar Power WA.',
    price: 0,
    billing_cycle: 'monthly',
    sort_order: 0,
    max_users: 1,
    max_contacts: 100,
    max_wa_instances: 1,
    max_templates: 5,
    max_broadcasts_per_month: 0,
    max_recipients_per_broadcast: 0,
    max_scheduled_messages: 0,
    max_deals: 0,
    max_tags: 3,
    max_webhook_configs: 0,
    daily_message_limit: 50,
    max_import_batch_size: 0,
    max_storage_mb: 100,
    analytics_max_days: 7,
    features: {
      broadcast: false,
      scheduledMessages: false,
      deals: false,
      closingReport: false,
      autoResponseNewChat: false,
      autoResponseOutsideHours: false,
      webhookConfigs: false,
      webhookAutoReply: false,
      teamManagement: false,
      assignConversation: false,
      conversationLabels: false,
      conversationPriority: false,
      contactImport: false,
      contactCustomFields: false,
      editMessage: false,
      analyticsMessageVolume: false,
      analyticsAgentPerformance: false,
      analyticsContactGrowth: false,
      apiAccess: false,
      scheduleBroadcast: false,
      broadcastMedia: false,
    },
  },
  {
    plan_code: 'STARTER' as const,
    name: 'Starter',
    description: 'Cocok untuk bisnis kecil yang ingin mulai menggunakan WhatsApp CRM.',
    price: 199_000,
    billing_cycle: 'monthly',
    sort_order: 1,
    max_users: 3,
    max_contacts: 1_000,
    max_wa_instances: 2,
    max_templates: 20,
    max_broadcasts_per_month: 5,
    max_recipients_per_broadcast: 100,
    max_scheduled_messages: 0,
    max_deals: 50,
    max_tags: 10,
    max_webhook_configs: 0,
    daily_message_limit: 500,
    max_import_batch_size: 100,
    max_storage_mb: 1_024,
    analytics_max_days: 7,
    features: {
      broadcast: true,
      scheduledMessages: false,
      deals: true,
      closingReport: false,
      autoResponseNewChat: true,
      autoResponseOutsideHours: false,
      webhookConfigs: false,
      webhookAutoReply: false,
      teamManagement: false,
      assignConversation: true,
      conversationLabels: true,
      conversationPriority: false,
      contactImport: true,
      contactCustomFields: false,
      editMessage: true,
      analyticsMessageVolume: true,
      analyticsAgentPerformance: false,
      analyticsContactGrowth: false,
      apiAccess: false,
      scheduleBroadcast: false,
      broadcastMedia: true,
    },
  },
  {
    plan_code: 'PROFESSIONAL' as const,
    name: 'Professional',
    description: 'Untuk tim yang butuh fitur lengkap: broadcast, scheduling, analytics, dan webhook.',
    price: 499_000,
    billing_cycle: 'monthly',
    sort_order: 2,
    max_users: 10,
    max_contacts: 10_000,
    max_wa_instances: 5,
    max_templates: 100,
    max_broadcasts_per_month: 30,
    max_recipients_per_broadcast: 1_000,
    max_scheduled_messages: 5,
    max_deals: -1,
    max_tags: -1,
    max_webhook_configs: 2,
    daily_message_limit: 2_000,
    max_import_batch_size: 1_000,
    max_storage_mb: 5_120,
    analytics_max_days: 30,
    features: {
      broadcast: true,
      scheduledMessages: true,
      deals: true,
      closingReport: true,
      autoResponseNewChat: true,
      autoResponseOutsideHours: true,
      webhookConfigs: true,
      webhookAutoReply: false,
      teamManagement: true,
      assignConversation: true,
      conversationLabels: true,
      conversationPriority: true,
      contactImport: true,
      contactCustomFields: true,
      editMessage: true,
      analyticsMessageVolume: true,
      analyticsAgentPerformance: true,
      analyticsContactGrowth: true,
      apiAccess: false,
      scheduleBroadcast: true,
      broadcastMedia: true,
    },
  },
  {
    plan_code: 'ENTERPRISE' as const,
    name: 'Enterprise',
    description: 'Unlimited — semua fitur terbuka, cocok untuk perusahaan besar.',
    price: 999_000,
    billing_cycle: 'monthly',
    sort_order: 3,
    max_users: -1,
    max_contacts: -1,
    max_wa_instances: -1,
    max_templates: -1,
    max_broadcasts_per_month: -1,
    max_recipients_per_broadcast: -1,
    max_scheduled_messages: -1,
    max_deals: -1,
    max_tags: -1,
    max_webhook_configs: -1,
    daily_message_limit: -1,
    max_import_batch_size: 1_000,
    max_storage_mb: 51_200,
    analytics_max_days: 90,
    features: {
      broadcast: true,
      scheduledMessages: true,
      deals: true,
      closingReport: true,
      autoResponseNewChat: true,
      autoResponseOutsideHours: true,
      webhookConfigs: true,
      webhookAutoReply: true,
      teamManagement: true,
      assignConversation: true,
      conversationLabels: true,
      conversationPriority: true,
      contactImport: true,
      contactCustomFields: true,
      editMessage: true,
      analyticsMessageVolume: true,
      analyticsAgentPerformance: true,
      analyticsContactGrowth: true,
      apiAccess: true,
      scheduleBroadcast: true,
      broadcastMedia: true,
    },
  },
];

async function main() {
  console.log('🌱 Seeding subscription plans...');

  for (const plan of plans) {
    const result = await prisma.subscriptionPlan.upsert({
      where: { plan_code: plan.plan_code },
      update: {
        name: plan.name,
        description: plan.description,
        price: plan.price,
        billing_cycle: plan.billing_cycle,
        sort_order: plan.sort_order,
        max_users: plan.max_users,
        max_contacts: plan.max_contacts,
        max_wa_instances: plan.max_wa_instances,
        max_templates: plan.max_templates,
        max_broadcasts_per_month: plan.max_broadcasts_per_month,
        max_recipients_per_broadcast: plan.max_recipients_per_broadcast,
        max_scheduled_messages: plan.max_scheduled_messages,
        max_deals: plan.max_deals,
        max_tags: plan.max_tags,
        max_webhook_configs: plan.max_webhook_configs,
        daily_message_limit: plan.daily_message_limit,
        max_import_batch_size: plan.max_import_batch_size,
        max_storage_mb: plan.max_storage_mb,
        analytics_max_days: plan.analytics_max_days,
        features: plan.features,
      },
      create: plan,
    });
    console.log(`  ✅ ${result.plan_code} — ${result.name} (Rp ${result.price.toLocaleString('id-ID')})`);
  }

  console.log('\n🎉 Seed complete — 4 plans upserted.');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
